public enum ScreenNamesAndDescriptions {
    HOME,
    SETTINGS,
    CART,
    PRODUCTS_LIST,
    FORGOT_PASSWORD,
    SIGN_UP,
    AUTHORIZATION_SCREEN,

    HOME_DESCRIPTION,
    SETTINGS_DESCRIPTION,
    CART_DESCRIPTION,
    PRODUCTS_LIST_DESCRIPTION,
    FORGOT_PASSWORD_DESCRIPTION,
    SIGN_UP_DESCRIPTION,
    AUTHORIZATION_SCREEN_DESCRIPTION

}
